# Notes:
# For bearing candidates, I instead want that to be a list of bearing
# bases that my teammates can fill in and I can set different bearings to use different bases.
# What's with the "-" usage; when does YAML use those and when not? Also,
# in my VSCode for floats the numbers after the "." are a different color. Why? Does it matter?
# Also I want to make shafts have a shaft base as well.
# For the bases, make sure I can set different elements to have different bases and it sets their base based on that, you know?
frame:
  origin_note: "Origin at splay shaft center; z at MCP joint center."
  axes:
    x: "distal"
    y: "right"
    z: "up"

# units: mm
geometry:
  splay_link_length: 25.0
  proximal_link_length: 40.0
  middle_link_length: 25.0
  distal_link_length: 25.0
  fingertip_offset: 10.0
  coupling_ratio: 0.7

bearing_bases:
  - part: "bearing_name"
    inner_diameter: 4.0
    outer_diameter: 11.0
    width: 4.0
    C_N: 75.0
    C0_N: 31.0
    X: 1.0
    Y: 0.0
    p: 3.0
    type: "deep_groove_ball"
    notes: "Make sure to fill in C/C0 from catalogue."

pulley_bases:
  - part: "pulley_name"
    radius: 6.0
    width: 3.0

shaft_bases:
  - part: "shaft_name"
    diameter: 4.0
    length: 25.0

shafts:
  - {name: "joint_Z", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}
  - {name: "joint_0", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}
  - {name: "joint_0", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}
  - {name: "joint_0", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}
  - {name: "joint_0", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}
  - {name: "joint_0", center: [0.0, 0.0, 0.0], axis: [0.0, 0.0, 1.0], dof_row: 0, alias: "splay"}


