import numpy as np
import matplotlib.pyplot as plt
import open3d as o3d
import trimesh

# Credit to Micheal Jenz for the code for transforming the workspace to an .stl

# Compute Workspace (possible end-effector locations for surgeon finger)
# Compute .stl for workspace

# Additional Notes:
# 0,0,0 is defined as the fingertip position at home config ( -> 👈)
# Flexion is negative z
# Hence the points generated on the graph are end-effector (fingertip) points 

# Basic Kinematics Defintions.
# copy and paste constants (kinematics.ino)

L_SPLAY = 24.0
L_MCP   = 44.0
L_PIP   = 39.0
L_DIP   = 22.0
 
R_PULLEY_PIP_DIP = 6.35 + 0.2794
R_PULLEY_DIP     = 9.0  + 0.2794
DIP_COUPLING     = R_PULLEY_PIP_DIP / R_PULLEY_DIP   # ~0.682

SPLAY_MIN, SPLAY_MAX = -10.0,  10.0   # deg
MCP_MIN,   MCP_MAX   = -90.0,   0.0   # deg  (negative = flexion)
PIP_MIN,   PIP_MAX   = -90.0,   0.0   # deg

def fk(q_splay, q_mcp, q_pip):
    #Exact replica of getForwardKinematics() in Kinematics.ino
    q_dip = q_pip * DIP_COUPLING
 
    a1 = np.radians(q_mcp)
    a2 = np.radians(q_mcp + q_pip)
    a3 = np.radians(q_mcp + q_pip + q_dip)
    sr = np.radians(q_splay)
 
    x_planar = L_SPLAY + L_MCP*np.cos(a1) + L_PIP*np.cos(a2) + L_DIP*np.cos(a3)
    z_planar =           L_MCP*np.sin(a1) + L_PIP*np.sin(a2) + L_DIP*np.sin(a3)
 
    x = L_SPLAY + L_MCP + L_PIP + L_DIP - (x_planar * np.cos(sr))
    y = x_planar * np.sin(sr)
    z = z_planar
    return x, y, z

# Sample Joint Spaces

N = 55 #no. steps 

#init splay values
splay_vals = np.linspace(SPLAY_MIN,SPLAY_MAX,N)
mcp_vals = np.linspace(MCP_MIN,MCP_MAX,N)
pip_vals = np.linspace(PIP_MIN,PIP_MAX,N)

#set configurations
home = fk(0,0,0)
full_flex = fk(0,MCP_MIN,PIP_MIN)
half_flex = fk(0,MCP_MIN*.5,PIP_MIN*.5)
splay_pos = fk(SPLAY_MAX, -45, -45) 
splay_neg = fk(SPLAY_MIN, -45, -45) 
xs, ys, zs = [], [], []
mcp_color  = []
points = []

#iterate for each splay, mcp, pip combination and dip
#foward kinematics for each 
for qs in splay_vals:
    for qm in mcp_vals:
        for qp in pip_vals:
            x, y, z = fk(qs, qm, qp)
            xs.append(x); ys.append(y); zs.append(z)
            mcp_color.append(qm)
            points.append([x, y, z])

xs = np.array(xs); ys = np.array(ys); zs = np.array(zs)
mcp_color = np.array(mcp_color)

print("=== Workspace Statistics ===")
print(f"X range: {xs.min():.1f} → {xs.max():.1f} mm  (span {xs.max()-xs.min():.1f} mm)")
print(f"Y range: {ys.min():.1f} → {ys.max():.1f} mm  (span {ys.max()-ys.min():.1f} mm)")
print(f"Z range: {zs.min():.1f} → {zs.max():.1f} mm  (span {zs.max()-zs.min():.1f} mm)")
print(f"\nKey poses (x, y, z) mm:")
print(f"  Home (extended)  : {home[0]:.1f}, {home[1]:.1f}, {home[2]:.1f}")
print(f"  Full flex        : {full_flex[0]:.1f}, {full_flex[1]:.1f}, {full_flex[2]:.1f}")
print(f"  Half flex        : {half_flex[0]:.1f}, {half_flex[1]:.1f}, {half_flex[2]:.1f}")
print(f"  Splay +10 deg    : {splay_pos[0]:.1f}, {splay_pos[1]:.1f}, {splay_pos[2]:.1f}")
print(f"  Splay -10 deg    : {splay_neg[0]:.1f}, {splay_neg[1]:.1f}, {splay_neg[2]:.1f}")
print(f"\nDIP coupling ratio: {DIP_COUPLING:.4f}")
print(f"Max DIP angle at full PIP flex: {-90*DIP_COUPLING:.1f} deg")
 
#disclaimer: plot generated by claude

# ── Plot ───────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 12), facecolor='#1a1a2e')
 
# colour map: MCP 0 (blue/extended) → -90 (red/flexed)
cmap = plt.cm.plasma
norm = plt.Normalize(MCP_MIN, MCP_MAX)
colors = cmap(norm(mcp_color))
 
# --- 3D scatter ---
ax3d = fig.add_subplot(2, 3, (1, 4), projection='3d')
ax3d.set_facecolor('#1a1a2e')
sc = ax3d.scatter(xs, ys, zs, c=mcp_color, cmap='plasma',
                  vmin=MCP_MIN, vmax=MCP_MAX,
                  s=1.2, alpha=0.25, rasterized=True)
# Key poses
for pos, label, col in [
    (home,      'Home',      'cyan'),
    (full_flex, 'Full flex', 'lime'),
    (half_flex, 'Half flex', 'yellow'),
]:
    ax3d.scatter(*pos, color=col, s=80, zorder=10)
    ax3d.text(pos[0]+1, pos[1]+1, pos[2]+1, label, color=col, fontsize=8)
 
ax3d.set_xlabel('X (mm)', color='white', labelpad=6)
ax3d.set_ylabel('Y (mm)', color='white', labelpad=6)
ax3d.set_zlabel('Z (mm)', color='white', labelpad=6)
ax3d.set_title('3D Workspace', color='white', fontsize=13, pad=12)
ax3d.tick_params(colors='white')
ax3d.xaxis.pane.fill = ax3d.yaxis.pane.fill = ax3d.zaxis.pane.fill = False
cbar = fig.colorbar(sc, ax=ax3d, shrink=0.5, pad=0.08)
cbar.set_label('MCP angle (°)', color='white')
cbar.ax.yaxis.set_tick_params(color='white')
plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')
 
# --- XZ plane (side view — sagittal, splay=0) ---
ax_xz = fig.add_subplot(2, 3, 2)
ax_xz.set_facecolor('#12122a')
mask = np.abs(ys) < 3.0   # near splay=0 slice
sc2 = ax_xz.scatter(xs[mask], zs[mask], c=mcp_color[mask], cmap='plasma',
                     vmin=MCP_MIN, vmax=MCP_MAX, s=2, alpha=0.4)
ax_xz.scatter(home[0], home[2], color='cyan', s=60, zorder=5, label='Home')
ax_xz.scatter(full_flex[0], full_flex[2], color='lime', s=60, zorder=5, label='Full flex')
ax_xz.set_xlabel('X – extension direction (mm)', color='white')
ax_xz.set_ylabel('Z – flexion direction (mm)', color='white')
ax_xz.set_title('Side View (Sagittal plane, splay≈0)', color='white')
ax_xz.tick_params(colors='white'); ax_xz.set_facecolor('#12122a')
ax_xz.spines[:].set_color('#555')
ax_xz.legend(fontsize=8, facecolor='#1a1a2e', labelcolor='white')
ax_xz.grid(True, color='#333')
 
# --- XY plane (top view — splay sweep, mid flex) ---
ax_xy = fig.add_subplot(2, 3, 3)
ax_xy.set_facecolor('#12122a')
mask2 = (np.abs(zs - half_flex[2]) < 4.0)
sc3 = ax_xy.scatter(xs[mask2], ys[mask2], c=mcp_color[mask2], cmap='plasma',
                     vmin=MCP_MIN, vmax=MCP_MAX, s=2, alpha=0.4)
ax_xy.scatter(splay_pos[0], splay_pos[1], color='orange', s=60, zorder=5, label='+10° splay')
ax_xy.scatter(splay_neg[0], splay_neg[1], color='magenta', s=60, zorder=5, label='−10° splay')
ax_xy.set_xlabel('X (mm)', color='white')
ax_xy.set_ylabel('Y – splay direction (mm)', color='white')
ax_xy.set_title('Top View (XY plane, mid flex slice)', color='white')
ax_xy.tick_params(colors='white')
ax_xy.spines[:].set_color('#555')
ax_xy.legend(fontsize=8, facecolor='#1a1a2e', labelcolor='white')
ax_xy.grid(True, color='#333')
 
# --- Reachable arc at splay=0: full MCP/PIP sweep finger silhouette ---
ax_arc = fig.add_subplot(2, 3, 5)
ax_arc.set_facecolor('#12122a')
 
mcp_fine = np.linspace(0, -90, 60)
pip_fine = np.linspace(0, -90, 60)
MM, PP = np.meshgrid(mcp_fine, pip_fine)
XX = np.zeros_like(MM); ZZ = np.zeros_like(MM)
for i in range(MM.shape[0]):
    for j in range(MM.shape[1]):
        x,y,z = fk(0, MM[i,j], PP[i,j])
        XX[i,j] = x; ZZ[i,j] = z
 
sc4 = ax_arc.contourf(XX, ZZ, MM, levels=20, cmap='plasma')
ax_arc.set_xlabel('X (mm)', color='white')
ax_arc.set_ylabel('Z (mm)', color='white')
ax_arc.set_title('Sagittal Coverage (splay=0)\nColour = MCP angle', color='white')
ax_arc.tick_params(colors='white'); ax_arc.spines[:].set_color('#555')
ax_arc.grid(True, color='#333')
cb2 = fig.colorbar(sc4, ax=ax_arc)
cb2.set_label('MCP (°)', color='white')
cb2.ax.yaxis.set_tick_params(color='white')
plt.setp(cb2.ax.yaxis.get_ticklabels(), color='white')
 
# --- Stats text box ---
ax_txt = fig.add_subplot(2, 3, 6)
ax_txt.set_facecolor('#12122a')
ax_txt.axis('off')
stats = (
    f"  WORKSPACE SUMMARY\n"
    f"  ─────────────────────────\n"
    f"  Link lengths (mm)\n"
    f"    Splay offset : {L_SPLAY:.0f}\n"
    f"    MCP          : {L_MCP:.0f}\n"
    f"    PIP          : {L_PIP:.0f}\n"
    f"    DIP          : {L_DIP:.0f}\n"
    f"    Total reach  : {L_MCP+L_PIP+L_DIP:.0f}\n\n"
    f"  Joint limits\n"
    f"    Splay  : {SPLAY_MIN:.0f}° → {SPLAY_MAX:.0f}°\n"
    f"    MCP    : {MCP_MIN:.0f}° → {MCP_MAX:.0f}°\n"
    f"    PIP    : {PIP_MIN:.0f}° → {PIP_MAX:.0f}°\n"
    f"    DIP    : coupled × {DIP_COUPLING:.3f}\n"
    f"           = 0° → {-90*DIP_COUPLING:.1f}°\n\n"
    f"  Cartesian extents\n"
    f"    X : {xs.min():.1f} → {xs.max():.1f} mm\n"
    f"    Y : {ys.min():.1f} → {ys.max():.1f} mm\n"
    f"    Z : {zs.min():.1f} → {zs.max():.1f} mm\n\n"
    f"  Key positions (mm)\n"
    f"    Home     : ({home[0]:.0f}, {home[1]:.0f}, {home[2]:.0f})\n"
    f"    Full flex: ({full_flex[0]:.0f}, {full_flex[1]:.0f}, {full_flex[2]:.0f})\n"
    f"    Half flex: ({half_flex[0]:.0f}, {half_flex[1]:.0f}, {half_flex[2]:.0f})\n"
)
ax_txt.text(0.02, 0.98, stats, transform=ax_txt.transAxes,
            fontsize=9.5, verticalalignment='top', fontfamily='monospace',
            color='white', linespacing=1.6)
 
plt.suptitle('RDS-26 Surgeon Finger — Workspace Analysis', 
             color='white', fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('C:/Users/Nicholas/RDS-26-Surgeon/control/scripts/workspace.png', dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
print("\nSaved to workspace.png")

### Addition: .stl of workspace for drawing demo

print("Starting Mesh")
pcd = o3d.geometry.PointCloud()
pcd.points  = o3d.utility.Vector3dVector(points)
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=15.0, max_nn=50))
pcd.orient_normals_consistent_tangent_plane(30)


pcd.orient_normals_towards_camera_location(pcd.get_center())

mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
    pcd, depth=9, width=0, scale=1.1, linear_fit=False
)

density_arr = np.asarray(densities)
keep = density_arr > np.percentile(density_arr, 5)
mesh = mesh.select_by_index(np.where(keep)[0])
# mesh.compute_vertex_normals()

# Clean up degenerate geometry

mesh.remove_degenerate_triangles()
mesh.remove_duplicated_triangles()
mesh.remove_duplicated_vertices()
mesh.remove_non_manifold_edges()

mesh.paint_uniform_color([0.2, 0.6, 0.75]) #paint steel-ish color

mesh.compute_vertex_normals()
mesh.orient_triangles()

o3d.io.write_triangle_mesh("C:/Users/Nicholas/RDS-26-Surgeon/control/scripts/workspace.stl", mesh)
print("Saved")

print("Building demo drawing plane")


plane_mesh = o3d.geometry.TriangleMesh.create_box(width=80.0, height=0.5, depth=60.0)
plane_mesh.translate([40.0, -30.0, -90.0])   # X: 40-120, Y:-30-+30, Z≈-90 (reachable)
plane_mesh.paint_uniform_color([0.95, 0.95, 0.80])
theta = np.radians(30)
R = plane_mesh.get_rotation_matrix_from_xyz((theta, 0, 0))
plane_mesh.rotate(R, center=(0, 0, 0))
plane_mesh.compute_vertex_normals()
o3d.io.write_triangle_mesh("C:/Users/Nicholas/RDS-26-Surgeon/control/scripts/drawing_space.stl", plane_mesh)